name: Upload to S3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy file to S3
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws_s3_bucket: ${{ secrets.AWS_S3BUCKET_NAME }}
          aws_cloudfront: ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}}
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region us-east-1
          aws s3 cp . s3://$aws_s3_bucket/
          aws cloudfront create-invalidation --distribution-id=$aws_cloudfront --paths "/*"